scriptSigningKey: "123456"
auth:
  httpsOnly: false
  jwt:
    username: admin
    password: HASH(qK+WLbw5urUSKEulOC6MEPUQbGscfcl3UWjQjLuJPJA=)
    passwordSalt: NaZCjLLzFNrqhHyiBuAwgw==
    secret: 234q9803b21KJHSAD)9832yhSdSUH9222fg234gefdsa11
    expirationMinutes: 1440
database:
  connectionString: h2:file:./webotix;DB_CLOSE_DELAY=-1;DEFAULT_LOCK_TIMEOUT=60000;DB_CLOSE_ON_EXIT=FALSE
telegram:
  botToken: 1383736175:AAEaML3a4hM1UUdHXaOi1uvAQWemsdlCcco
  chatId: 327871252
exchanges:
  binance:
    apiKey:
    secretKey:
    loadRemoteData: true
    enabled: true
jerseyClient:
  timeout: 5000ms
  connectionTimeout: 5000ms
  connectionRequestTimeout: 5000ms
server:
  type: simple
  rootPath: /api/
  applicationContextPath: /
  connector:
    type: http
    port: 8080
  maxThreads: 16
