database:
  connectionString: h2:file:./webotix;DB_CLOSE_DELAY=-1;DEFAULT_LOCK_TIMEOUT=60000
exchanges:
  simulated:
    apiKey: DEMO
  gdax:
    apiKey: 
    secretKey: 
    passphrase: 
    sandbox: false # default
    loadRemoteData: true # default. Disable if the exchange goes down to avoid spamming it for metadata requests
  binance:
    apiKey: 
    secretKey:
    loadRemoteData: true
  kucoin:
    apiKey: 
    secretKey: 
    passphrase: 
    sandbox: false
    loadRemoteData: true
  bitfinex:
    apiKey: 
    secretKey:
    loadRemoteData: true
  bitmex:
    apiKey: 
    secretKey: 
    loadRemoteData: true
  kraken:
    apiKey: 
    secretKey: 
    loadRemoteData: true
  bittrex:
    apiKey: 
    secretKey: 
    loadRemoteData: 
jerseyClient:
  timeout: 5000ms
  connectionTimeout: 5000ms
  connectionRequestTimeout: 5000ms
server:
  type: simple
  rootPath: /api/
  applicationContextPath: /
  connector:
    type: http
    port: 8080
  maxThreads: 16
