loopSeconds: ${LOOP_SECONDS:-15}
scriptSigningKey: '${SCRIPT_SIGNING_KEY:-}${secret-script-signing-key}'
auth:
  httpsOnly: ${HTTPS:-false}
  jwt:
    username: '${SIMPLE_AUTH_USERNAME:-}${secret-jwt-username}'
    password: '${SIMPLE_AUTH_PASSWORD:-}${secret-jwt-password}'
    passwordSalt: '${SIMPLE_AUTH_SALT:-}${secret-jwt-salt}'
    secret: '${SIMPLE_AUTH_SECRET:-}${secret-jwt-signing-key}'
    expirationMinutes: ${SIMPLE_AUTH_TOKEN_EXPIRY_MINUTES:-1440}
telegram:
  botToken: '${TELEGRAM_BOT_TOKEN:-}${secret-telegram-botToken}'
  chatId: '${TELEGRAM_CHAT_ID:-}${secret-telegram-chatId}'
database:
  connectionString: ${JDBC_URL:-h2:file:/app/db/webotix;DB_CLOSE_DELAY=-1;AUTO_SERVER=true;DEFAULT_LOCK_TIMEOUT=60000}
  lockSeconds: ${LOCK_SECONDS:-45}
exchanges:
  binance:
    apiKey: '${BINANCE_API_KEY:-}${secret-exchanges-binance-apiKey}'
    secretKey: '${BINANCE_SECRET:-}${secret-exchanges-binance-secretKey}'
    loadRemoteData: ${BINANCE_REMOTE_META:-true}
    enabled: true
server:
  type: simple
  rootPath: /api/
  applicationContextPath: /
  connector:
    type: http
    port: 8080
  requestLog:
    appenders: []
  maxThreads: 16
jerseyClient:
  timeout: 15000ms
  connectionTimeout: 15000ms
  connectionRequestTimeout: 15000ms
logging:
  loggers:
    "ru.webotix": ${LOG_LEVEL:-INFO}
    "info.bitrich.xchangestream.service.netty": ${LOG_LEVEL:-INFO}
    "info.bitrich.xchangestream.binance": ${LOG_LEVEL:-INFO}
    "info.bitrich.xchangestream.gdax": ${LOG_LEVEL:-INFO}
    "info.bitrich.xchangestream.binance.BinanceUserDataStreamingService": ${LOG_LEVEL_BINANCE_RAW_USER:-INFO}
    "si.mazi.rescu": ERROR
